version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    environment:
      - APP_HOST=backend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - mynet


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-backend
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mydatabase
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - mynet

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=myapp
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynet

volumes:
  postgres-data:

networks:
  mynet:
    driver: bridge